name: vizflow
recipe: drupal9
config:
  php: 8.1
  webroot: web
  composer_version: '2.0.2'

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - drupalcommerce.vizflow.internal
  drupalcommerce:
    type: mariadb
    portforward: true
    creds:
      user: drupalcommerce
      password: drupalcommerce
      database: drupalcommerce